### ISSUE TITLE
fail to parse mapping document

### ISSUE THREAD

**Issue by huanyu-li** [oeg-upm/morph-graphql#151]
Hi,

I'm trying to run morph-graphql with Node and get following error message after I submit. It seems the parsing mapping document step fails. Could you please help me figure out this issue? Thank you in advance.

Best,
Huanyu

$ node app.js 
Morph-GraphQL is listening on port 8082!
prog_lang = javascript
map_lang = r2rml
dataset_type = sqlite
mapping_url = https://raw.githubusercontent.com/oeg-upm/morph-graphql/master/examples/LinGBM/LinGBM.r2rml.ttl
database name = 123
port_no = 4321
queryplanner = joinmonster
PARSING MAPPING DOCUMENT FROM https://raw.githubusercontent.com/oeg-upm/morph-graphql/master/examples/LinGBM/LinGBM.r2rml.ttl ...
(node:67894) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.exports.get_jsonld_from_mapping (/Users/huali50/Downloads/morph-graphql-1.0.0/javascript/rdb/r2rml-parser.js:907:18)
    at create_resolver (/Users/huali50/Downloads/morph-graphql-1.0.0/javascript/rdb/app.js:238:28)
    at /Users/huali50/Downloads/morph-graphql-1.0.0/javascript/rdb/app.js:191:35
    at Layer.handle [as handle_request] (/Users/huali50/Downloads/morph-graphql-1.0.0/javascript/rdb/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/huali50/Downloads/morph-graphql-1.0.0/javascript/rdb/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/huali50/Downloads/morph-graphql-1.0.0/javascript/rdb/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/huali50/Downloads/morph-graphql-1.0.0/javascript/rdb/node_modules/express/lib/router/layer.js:95:5)
    at /Users/huali50/Downloads/morph-graphql-1.0.0/javascript/rdb/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/huali50/Downloads/morph-graphql-1.0.0/javascript/rdb/node_modules/express/lib/router/index.js:335:12)
(node:67894) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:67894) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dachafra** [comment]
Hi @huanyu-li thanks for being interested in using Morph-GraphQL, we will take a look today or tomorrow. Bests!

**Comment by daniel-dona** [comment]
This bug is confirmed, I'm working on it. The problem is an external dependency that converts TTL to JSON-LD.

**Comment by dachafra** [comment]
thanks @daniel-dona !

**Comment by kishorsn77** [comment]
Hi @daniel-dona , I am having same issue mentioned above. Any update when this fix will be available? 
Meanwhile, if you can share any workaround, that will be helpful.

**Comment by dachafra** [comment]
Dear @kishorsn77 @huanyu-li, thanks for your interest in Morph-GraphQL. Unfortunately, due to the lack of human resources we have right now, we have decided to deprecate the code and it is not in our short term to give support for solving the issues. Of course, any help will be more than welcome!
